import {
  useEffect, useRef, useState,
  type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode,
} from 'react'
import { useNavigate } from 'react-router-dom'
import { useT } from '../i18n/I18nProvider.js'
import { useVoiceInput } from '../lib/useVoiceInput.js'

type Variant = 'primary' | 'ghost' | 'quiet' | 'danger' | 'accent'
export function Button({ variant='primary',size,className='',children,...rest }: ButtonHTMLAttributes<HTMLButtonElement>&{variant?:Variant;size?:'sm'}) { const v:Record<Variant,string>={primary:'',ghost:'btn--ghost',quiet:'btn--quiet',danger:'btn--danger',accent:'btn--accent'}; return <button type="button" className={`btn ${v[variant]} ${size==='sm'?'btn--sm':''} ${className}`} {...rest}>{children}</button> }
export function AppBar({title,sub,onBack,right,backTo}:{title:ReactNode;sub?:ReactNode;onBack?:()=>void;right?:ReactNode;backTo?:string}) { const nav=useNavigate(); return <header className="appbar">{(onBack||backTo)&&<button className="appbar__btn" aria-label="Back" onClick={()=>onBack?onBack():nav(backTo!)}>←</button>}<h1 className="appbar__title">{title}{sub&&<span className="appbar__sub">{sub}</span>}</h1>{right}</header> }
/** Read-aloud/text-to-speech has been intentionally removed from the product UI. Kept as a no-op export so existing screens remain source-compatible. */
export function AudioHelpButton(_props:{text:string}) { return null }
export function Card({className='',children,...rest}:React.HTMLAttributes<HTMLDivElement>) { return <div className={`card ${className}`} {...rest}>{children}</div> }
export function SectionTitle({children,action}:{children:ReactNode;action?:ReactNode}) { return <div className="row-between" style={{marginBottom:'var(--s2)'}}><h2 className="section-title" style={{margin:0}}>{children}</h2>{action}</div> }
export function Notice({tone='info',title,children}:{tone?:'info'|'warn'|'ok'|'danger';title?:ReactNode;children:ReactNode}) { return <div className={`notice notice--${tone}`}>{title&&<strong className="notice__title">{title}</strong>}{children}</div> }
export function Pill({tone='neutral',icon,children}:{tone?:'neutral'|'info'|'warn'|'ok'|'danger';icon?:ReactNode;children:ReactNode}) { return <span className={`pill pill--${tone}`}>{icon&&<span aria-hidden="true">{icon}</span>}{children}</span> }
export function EmptyState({icon='📭',title,body,action}:{icon?:string;title:ReactNode;body?:ReactNode;action?:ReactNode}) { return <div className="empty"><div className="empty__icon" aria-hidden="true">{icon}</div><div className="empty__title">{title}</div>{body&&<div className="empty__body">{body}</div>}{action}</div> }
export function Loading() { const t=useT(); return <div className="empty"><div className="empty__icon" aria-hidden="true">⏳</div><div className="empty__body">{t('common.loading')}</div></div> }
export function Field({label,hint,error,required,children,htmlFor}:{label?:ReactNode;hint?:ReactNode;error?:string;required?:boolean;children:ReactNode;htmlFor?:string}) { return <div className="field">{label&&<label className="field__label" htmlFor={htmlFor}>{label}{required&&<span className="field__req" aria-hidden="true">*</span>}</label>}{hint&&<div className="field__hint">{hint}</div>}{children}{error&&<div className="field__err" role="alert">⚠ {error}</div>}</div> }
export function TextInput({error,...rest}:InputHTMLAttributes<HTMLInputElement>&{error?:boolean}) { return <input className={`input ${error?'input--err':''}`} {...rest}/> }
export function VoiceInput({value,onChange,error,multiline,lang='mr-IN',...rest}:{value:string;onChange:(v:string)=>void;error?:boolean;multiline?:boolean;lang?:string}&Omit<InputHTMLAttributes<HTMLInputElement>,'value'|'onChange'>) { const t=useT(); const {supported,listening,error:voiceError,interim,toggle}=useVoiceInput((said)=>onChange(value?`${value} ${said}`:said),{lang}); const errorText=voiceError==='denied'?t('common.voiceUnsupported'):voiceError==='no-speech'?t('common.speak'):null; return <div className="stack-sm"><div className="input-voice">{multiline?<textarea className={`textarea ${error?'textarea--err':''}`} value={listening&&interim?`${value} ${interim}`.trim():value} onChange={e=>onChange(e.target.value)} {...(rest as React.TextareaHTMLAttributes<HTMLTextAreaElement>)}/>:<input className={`input ${error?'input--err':''}`} value={listening&&interim?`${value} ${interim}`.trim():value} onChange={e=>onChange(e.target.value)} {...rest}/>} {supported&&<button type="button" className={`mic ${listening?'mic--on':''}`} onClick={toggle} aria-label={listening?t('common.listening'):t('common.voiceHint')} aria-pressed={listening}>{listening?'⏹':'🎤'}</button>}</div>{supported&&<div className="tiny dim">{listening?`🔴 ${t('common.listening')}`:`🎤 ${t('common.voiceHint')}`}</div>}{errorText&&<div className="field__err">⚠ {errorText}</div>}</div> }
export function Choice({selected,onSelect,title,sub,icon,disabled}:{selected:boolean;onSelect:()=>void;title:ReactNode;sub?:ReactNode;icon?:ReactNode;disabled?:boolean}) { return <button type="button" className={`choice ${selected?'choice--on':''}`} onClick={onSelect} disabled={disabled} aria-pressed={selected}><span className="choice__mark" aria-hidden="true">{selected?'✓':''}</span><span className="choice__body">{icon&&<span aria-hidden="true" style={{marginRight:8}}>{icon}</span>}{title}{sub&&<span className="choice__sub">{sub}</span>}</span></button> }
export function YesNo({value,onChange}:{value:boolean|null;onChange:(v:boolean)=>void}) { const t=useT(); return <div className="yesno"><Choice selected={value===true} onSelect={()=>onChange(true)} icon="👍" title={t('common.yes')}/><Choice selected={value===false} onSelect={()=>onChange(false)} icon="👎" title={t('common.no')}/></div> }
export function Stepper({value,onChange,min=1,max=99}:{value:number;onChange:(v:number)=>void;min?:number;max?:number}) { return <div className="stepper"><button onClick={()=>onChange(Math.max(min,value-1))} disabled={value<=min} aria-label="−">−</button><span className="stepper__v">{value}</span><button onClick={()=>onChange(Math.min(max,value+1))} disabled={value>=max} aria-label="+">+</button></div> }
export function SlotMeter({used,total,hint}:{used:number;total:number;hint?:ReactNode}) { const t=useT(); const n=Math.max(total,1); return <div className="slotmeter"><div className="row-between"><strong>{t('biz.myProducts')}</strong><span className="num dim">{used} / {total}</span></div><div className="slotmeter__bars" style={{gridTemplateColumns:`repeat(${n}, 1fr)`}}>{Array.from({length:n}).map((_,i)=><div key={i} className={`slotmeter__bar ${i<used?'slotmeter__bar--on':''}`}/>)}</div>{hint&&<div className="small dim">{hint}</div>}</div> }
export function Dots({step,total}:{step:number;total:number}) { return <div className="dots" role="progressbar" aria-valuenow={step+1} aria-valuemax={total}>{Array.from({length:total}).map((_,i)=><div key={i} className={`dots__d ${i===step?'dots__d--on':''} ${i<step?'dots__d--done':''}`}/>)}</div> }
export function OtpInput({value,onChange,length=4}:{value:string;onChange:(v:string)=>void;length?:number}) { const refs=useRef<(HTMLInputElement|null)[]>([]); function setAt(i:number,ch:string){const digits=value.padEnd(length,' ').split('');digits[i]=ch;onChange(digits.join('').replace(/\s/g,''));if(ch&&i<length-1)refs.current[i+1]?.focus()} return <div className="otp">{Array.from({length}).map((_,i)=><input key={i} ref={el=>{refs.current[i]=el}} inputMode="numeric" maxLength={1} value={value[i]??''} onChange={e=>setAt(i,e.target.value.replace(/\D/g,''))} onKeyDown={e=>{if(e.key==='Backspace'&&!value[i]&&i>0)refs.current[i-1]?.focus()}} aria-label={`OTP digit ${i+1}`}/>)}</div> }
export function Rupees({value,className=''}:{value:number;className?:string}) { return <span className={`num ${className}`}>₹{Number(value||0).toLocaleString('en-IN')}</span> }
export function ConfirmSheet({open,title,body,confirmLabel,tone='primary',onConfirm,onCancel}:{open:boolean;title:ReactNode;body?:ReactNode;confirmLabel?:ReactNode;tone?:'primary'|'danger';onConfirm:()=>void;onCancel:()=>void}) { const t=useT();if(!open)return null;return <div className="sheet-backdrop" onClick={onCancel}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="stack"><div className="stack-sm"><h2 className="h2">{title}</h2>{body&&<p className="body muted">{body}</p>}</div><div className="btn-row"><Button variant="quiet" onClick={onCancel}>{t('common.cancel')}</Button><Button variant={tone==='danger'?'danger':'primary'} onClick={onConfirm}>{confirmLabel??t('common.confirm')}</Button></div></div></div></div> }
export function useAsync<T>(fn:()=>Promise<T>,deps:unknown[]=[]):[T|null,boolean,(d:T)=>void] { const [state,setState]=useState<{loading:boolean;data:T|null}>({loading:true,data:null});useEffect(()=>{let alive=true;setState(s=>({...s,loading:true}));fn().then(data=>alive&&setState({loading:false,data})).catch(()=>alive&&setState({loading:false,data:null}));return()=>{alive=false}},deps);return [state.data,state.loading,(d:T)=>setState({loading:false,data:d})] }
